<?php

namespace DoctrineProxies\__CG__\Billing\Domain\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SubscriptionEntity extends \Billing\Domain\Entities\SubscriptionEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'id', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'trialPeriodDays', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'usageCount', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'paymentGateway', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'externalId', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'createdAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'updatedAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'canceledAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'cancelAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'endedAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'renewAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'order', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'plan', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'workspace'];
        }

        return ['__isInitialized__', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'id', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'trialPeriodDays', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'usageCount', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'paymentGateway', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'externalId', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'createdAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'updatedAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'canceledAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'cancelAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'endedAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'renewAt', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'order', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'plan', '' . "\0" . 'Billing\\Domain\\Entities\\SubscriptionEntity' . "\0" . 'workspace'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SubscriptionEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): \Shared\Domain\ValueObjects\Id
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrialPeriodDays(): \Billing\Domain\ValueObjects\TrialPeriodDays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrialPeriodDays', []);

        return parent::getTrialPeriodDays();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsageCount(): \Billing\Domain\ValueObjects\Count
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsageCount', []);

        return parent::getUsageCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentGateway(): \Billing\Domain\ValueObjects\PaymentGateway
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentGateway', []);

        return parent::getPaymentGateway();
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalId(): \Billing\Domain\ValueObjects\ExternalId
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalId', []);

        return parent::getExternalId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCanceledAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanceledAt', []);

        return parent::getCanceledAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelAt', []);

        return parent::getCancelAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndedAt', []);

        return parent::getEndedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRenewAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRenewAt', []);

        return parent::getRenewAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder(): ?\Billing\Domain\Entities\OrderEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlan(): \Billing\Domain\Entities\PlanSnapshotEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlan', []);

        return parent::getPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function getCredit(): \Billing\Domain\ValueObjects\Count
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredit', []);

        return parent::getCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function deductCredit(\Billing\Domain\ValueObjects\Count $count): \Billing\Domain\ValueObjects\Count
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deductCredit', [$count]);

        return parent::deductCredit($count);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): \Billing\Domain\ValueObjects\SubscriptionStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function cancel(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cancel', []);

        parent::cancel();
    }

    /**
     * {@inheritDoc}
     */
    public function end(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'end', []);

        parent::end();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', []);

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function getWorkspace(): \Workspace\Domain\Entities\WorkspaceEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorkspace', []);

        return parent::getWorkspace();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function renew(): \Billing\Domain\Entities\SubscriptionEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'renew', []);

        return parent::renew();
    }

}
